In [4]:
import numpy as np
import matplotlib.pyplot as plt
np.warnings.filterwarnings('ignore')

In [7]:
# Решите линейную систему:

A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

In [8]:
# либо

A1 = np.linalg.inv(A)
print(A1)
print("Детерминант = {0}".format(np.linalg.det(A)))
np.dot(A1, B)

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]
Детерминант = 59.999999999999986


array([-9.2       ,  0.9       ,  6.46666667])

In [5]:
# Найдите псевдорешение:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])

np.linalg.lstsq(A, B)



(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))